#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://pnl.gov/RAA/Definition/", ConfigurationName="DefinitionSoap")]
public interface DefinitionSoap
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://pnl.gov/RAA/Definition/GetProcessDefnById", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ActorCriteria))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Activity))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Process))]
    System.Threading.Tasks.Task<DefnProcess> GetProcessDefnByIdAsync(int Id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://pnl.gov/RAA/Definition/GetProcessDefnByDocType", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ActorCriteria))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Activity))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Process))]
    System.Threading.Tasks.Task<DefnProcess> GetProcessDefnByDocTypeAsync(string DocType, int IRI);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://pnl.gov/RAA/Definition/GetProcessMetaDataXmlNodes", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ActorCriteria))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Activity))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Process))]
    System.Threading.Tasks.Task<System.Xml.Linq.XElement> GetProcessMetaDataXmlNodesAsync(int Id);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pnl.gov/RAA/Definition/")]
public partial class DefnProcess : Process
{
    
    private DefnActivity[] defnActivitiesField;
    
    private bool isEditLinkDisplayedField;
    
    private bool allowCasualUploadField;
    
    private string casualUploadRoleNameField;
    
    private bool isEnabledField;
    
    private int retentionPeriodQtyField;
    
    private string retentionPeriodUnitField;
    
    private bool notifyOriginatorOnApprovalField;
    
    private bool notifyBeneficiaryOnApprovalField;
    
    private bool notifySuperuserOnApprovalField;
    
    private bool notifyOriginatorOnRejectionField;
    
    private bool notifyBeneficiaryOnRejectionField;
    
    private bool notifySuperuserOnRejectionField;
    
    private string developerUserRoleNameField;
    
    private string readOnlyUserRoleNameField;
    
    private bool notifyOriginatorOnEscalationField;
    
    private bool notifyBeneficiaryOnEscalationField;
    
    private bool notifySuperuserOnEscalationField;
    
    private bool notifyOriginatorOnDelegationField;
    
    private bool notifyBeneficiaryOnDelegationField;
    
    private bool notifySuperuserOnDelegationField;
    
    private bool notifyOnSuperuserTerminationField;
    
    private bool allowUserNotificationPreferenceField;
    
    private bool notifyOnApplicationTerminationField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
    public DefnActivity[] DefnActivities
    {
        get
        {
            return this.defnActivitiesField;
        }
        set
        {
            this.defnActivitiesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public bool IsEditLinkDisplayed
    {
        get
        {
            return this.isEditLinkDisplayedField;
        }
        set
        {
            this.isEditLinkDisplayedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public bool AllowCasualUpload
    {
        get
        {
            return this.allowCasualUploadField;
        }
        set
        {
            this.allowCasualUploadField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string CasualUploadRoleName
    {
        get
        {
            return this.casualUploadRoleNameField;
        }
        set
        {
            this.casualUploadRoleNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public bool IsEnabled
    {
        get
        {
            return this.isEnabledField;
        }
        set
        {
            this.isEnabledField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public int RetentionPeriodQty
    {
        get
        {
            return this.retentionPeriodQtyField;
        }
        set
        {
            this.retentionPeriodQtyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=6)]
    public string RetentionPeriodUnit
    {
        get
        {
            return this.retentionPeriodUnitField;
        }
        set
        {
            this.retentionPeriodUnitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=7)]
    public bool NotifyOriginatorOnApproval
    {
        get
        {
            return this.notifyOriginatorOnApprovalField;
        }
        set
        {
            this.notifyOriginatorOnApprovalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=8)]
    public bool NotifyBeneficiaryOnApproval
    {
        get
        {
            return this.notifyBeneficiaryOnApprovalField;
        }
        set
        {
            this.notifyBeneficiaryOnApprovalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=9)]
    public bool NotifySuperuserOnApproval
    {
        get
        {
            return this.notifySuperuserOnApprovalField;
        }
        set
        {
            this.notifySuperuserOnApprovalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=10)]
    public bool NotifyOriginatorOnRejection
    {
        get
        {
            return this.notifyOriginatorOnRejectionField;
        }
        set
        {
            this.notifyOriginatorOnRejectionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=11)]
    public bool NotifyBeneficiaryOnRejection
    {
        get
        {
            return this.notifyBeneficiaryOnRejectionField;
        }
        set
        {
            this.notifyBeneficiaryOnRejectionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=12)]
    public bool NotifySuperuserOnRejection
    {
        get
        {
            return this.notifySuperuserOnRejectionField;
        }
        set
        {
            this.notifySuperuserOnRejectionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=13)]
    public string DeveloperUserRoleName
    {
        get
        {
            return this.developerUserRoleNameField;
        }
        set
        {
            this.developerUserRoleNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=14)]
    public string ReadOnlyUserRoleName
    {
        get
        {
            return this.readOnlyUserRoleNameField;
        }
        set
        {
            this.readOnlyUserRoleNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=15)]
    public bool NotifyOriginatorOnEscalation
    {
        get
        {
            return this.notifyOriginatorOnEscalationField;
        }
        set
        {
            this.notifyOriginatorOnEscalationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=16)]
    public bool NotifyBeneficiaryOnEscalation
    {
        get
        {
            return this.notifyBeneficiaryOnEscalationField;
        }
        set
        {
            this.notifyBeneficiaryOnEscalationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=17)]
    public bool NotifySuperuserOnEscalation
    {
        get
        {
            return this.notifySuperuserOnEscalationField;
        }
        set
        {
            this.notifySuperuserOnEscalationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=18)]
    public bool NotifyOriginatorOnDelegation
    {
        get
        {
            return this.notifyOriginatorOnDelegationField;
        }
        set
        {
            this.notifyOriginatorOnDelegationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=19)]
    public bool NotifyBeneficiaryOnDelegation
    {
        get
        {
            return this.notifyBeneficiaryOnDelegationField;
        }
        set
        {
            this.notifyBeneficiaryOnDelegationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=20)]
    public bool NotifySuperuserOnDelegation
    {
        get
        {
            return this.notifySuperuserOnDelegationField;
        }
        set
        {
            this.notifySuperuserOnDelegationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=21)]
    public bool NotifyOnSuperuserTermination
    {
        get
        {
            return this.notifyOnSuperuserTerminationField;
        }
        set
        {
            this.notifyOnSuperuserTerminationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=22)]
    public bool AllowUserNotificationPreference
    {
        get
        {
            return this.allowUserNotificationPreferenceField;
        }
        set
        {
            this.allowUserNotificationPreferenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=23)]
    public bool NotifyOnApplicationTermination
    {
        get
        {
            return this.notifyOnApplicationTerminationField;
        }
        set
        {
            this.notifyOnApplicationTerminationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pnl.gov/RAA/Definition/")]
public partial class DefnActivity : Activity
{
    
    private DefnBooleanTest[] defnBooleanTestsField;
    
    private DefnActorCriteria[] defnActorCriteriasField;
    
    private Relationship[] defnParentRelationshipsField;
    
    private Relationship[] defnChildRelationshipsField;
    
    private int defnProcessIdField;
    
    private bool notifyActedActorOnRejectionField;
    
    private bool notifyActedActorOnApprovalField;
    
    private bool notifyOtherActorsOnRejectionField;
    
    private bool notifyOtherActorsOnApprovalField;
    
    private bool notifyActorOnDelegationField;
    
    private bool neverNotifyActorsOnPendingField;
    
    private bool notifyActorsOnEscalationField;
    
    private bool isDelegateDesiredField;
    
    private int delegAuthIdField;
    
    private string delegAuthNameField;
    
    private int delegRoleIdField;
    
    private string delegRoleNameField;
    
    private ActivityDelegateState delegateObtainOnStateField;
    
    private bool isDelegateReplacementActorField;
    
    private string defnNodeNameField;
    
    private bool isScopeTreeActivityField;
    
    private int roleScopeTypeIdField;
    
    private int executionPackageIdField;
    
    private TypeOfReplication replicationTypeField;
    
    private bool displayInTaskListField;
    
    private bool allowBypassActorIsOriginatorField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
    public DefnBooleanTest[] DefnBooleanTests
    {
        get
        {
            return this.defnBooleanTestsField;
        }
        set
        {
            this.defnBooleanTestsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
    public DefnActorCriteria[] DefnActorCriterias
    {
        get
        {
            return this.defnActorCriteriasField;
        }
        set
        {
            this.defnActorCriteriasField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
    public Relationship[] DefnParentRelationships
    {
        get
        {
            return this.defnParentRelationshipsField;
        }
        set
        {
            this.defnParentRelationshipsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
    public Relationship[] DefnChildRelationships
    {
        get
        {
            return this.defnChildRelationshipsField;
        }
        set
        {
            this.defnChildRelationshipsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public int DefnProcessId
    {
        get
        {
            return this.defnProcessIdField;
        }
        set
        {
            this.defnProcessIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public bool NotifyActedActorOnRejection
    {
        get
        {
            return this.notifyActedActorOnRejectionField;
        }
        set
        {
            this.notifyActedActorOnRejectionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=6)]
    public bool NotifyActedActorOnApproval
    {
        get
        {
            return this.notifyActedActorOnApprovalField;
        }
        set
        {
            this.notifyActedActorOnApprovalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=7)]
    public bool NotifyOtherActorsOnRejection
    {
        get
        {
            return this.notifyOtherActorsOnRejectionField;
        }
        set
        {
            this.notifyOtherActorsOnRejectionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=8)]
    public bool NotifyOtherActorsOnApproval
    {
        get
        {
            return this.notifyOtherActorsOnApprovalField;
        }
        set
        {
            this.notifyOtherActorsOnApprovalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=9)]
    public bool NotifyActorOnDelegation
    {
        get
        {
            return this.notifyActorOnDelegationField;
        }
        set
        {
            this.notifyActorOnDelegationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=10)]
    public bool NeverNotifyActorsOnPending
    {
        get
        {
            return this.neverNotifyActorsOnPendingField;
        }
        set
        {
            this.neverNotifyActorsOnPendingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=11)]
    public bool NotifyActorsOnEscalation
    {
        get
        {
            return this.notifyActorsOnEscalationField;
        }
        set
        {
            this.notifyActorsOnEscalationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=12)]
    public bool IsDelegateDesired
    {
        get
        {
            return this.isDelegateDesiredField;
        }
        set
        {
            this.isDelegateDesiredField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=13)]
    public int DelegAuthId
    {
        get
        {
            return this.delegAuthIdField;
        }
        set
        {
            this.delegAuthIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=14)]
    public string DelegAuthName
    {
        get
        {
            return this.delegAuthNameField;
        }
        set
        {
            this.delegAuthNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=15)]
    public int DelegRoleId
    {
        get
        {
            return this.delegRoleIdField;
        }
        set
        {
            this.delegRoleIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=16)]
    public string DelegRoleName
    {
        get
        {
            return this.delegRoleNameField;
        }
        set
        {
            this.delegRoleNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=17)]
    public ActivityDelegateState DelegateObtainOnState
    {
        get
        {
            return this.delegateObtainOnStateField;
        }
        set
        {
            this.delegateObtainOnStateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=18)]
    public bool IsDelegateReplacementActor
    {
        get
        {
            return this.isDelegateReplacementActorField;
        }
        set
        {
            this.isDelegateReplacementActorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=19)]
    public string DefnNodeName
    {
        get
        {
            return this.defnNodeNameField;
        }
        set
        {
            this.defnNodeNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=20)]
    public bool IsScopeTreeActivity
    {
        get
        {
            return this.isScopeTreeActivityField;
        }
        set
        {
            this.isScopeTreeActivityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=21)]
    public int RoleScopeTypeId
    {
        get
        {
            return this.roleScopeTypeIdField;
        }
        set
        {
            this.roleScopeTypeIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=22)]
    public int ExecutionPackageId
    {
        get
        {
            return this.executionPackageIdField;
        }
        set
        {
            this.executionPackageIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=23)]
    public TypeOfReplication ReplicationType
    {
        get
        {
            return this.replicationTypeField;
        }
        set
        {
            this.replicationTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=24)]
    public bool DisplayInTaskList
    {
        get
        {
            return this.displayInTaskListField;
        }
        set
        {
            this.displayInTaskListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=25)]
    public bool AllowBypassActorIsOriginator
    {
        get
        {
            return this.allowBypassActorIsOriginatorField;
        }
        set
        {
            this.allowBypassActorIsOriginatorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pnl.gov/RAA/Definition/")]
public partial class DefnBooleanTest
{
    
    private string nodeNameField;
    
    private string nameField;
    
    private Operands operandField;
    
    private string comparisonValueField;
    
    private string validation_Type_CdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string NodeName
    {
        get
        {
            return this.nodeNameField;
        }
        set
        {
            this.nodeNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public Operands Operand
    {
        get
        {
            return this.operandField;
        }
        set
        {
            this.operandField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string ComparisonValue
    {
        get
        {
            return this.comparisonValueField;
        }
        set
        {
            this.comparisonValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public string Validation_Type_Cd
    {
        get
        {
            return this.validation_Type_CdField;
        }
        set
        {
            this.validation_Type_CdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pnl.gov/RAA/Definition/")]
public enum Operands
{
    
    /// <remarks/>
    EQ,
    
    /// <remarks/>
    NE,
    
    /// <remarks/>
    GT,
    
    /// <remarks/>
    LT,
    
    /// <remarks/>
    GE,
    
    /// <remarks/>
    LE,
    
    /// <remarks/>
    Contains,
    
    /// <remarks/>
    NotContains,
    
    /// <remarks/>
    StartsWith,
    
    /// <remarks/>
    NotStartsWith,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pnl.gov/RAA/Definition/")]
public partial class Relationship
{
    
    private int relationshipActivityIdField;
    
    private string relationshipActivityNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public int RelationshipActivityId
    {
        get
        {
            return this.relationshipActivityIdField;
        }
        set
        {
            this.relationshipActivityIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string RelationshipActivityName
    {
        get
        {
            return this.relationshipActivityNameField;
        }
        set
        {
            this.relationshipActivityNameField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(DefnActorCriteria))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pnl.gov/RAA/Definition/")]
public partial class ActorCriteria
{
    
    private string nameField;
    
    private string nodeNameField;
    
    private string roleNameField;
    
    private int executionPackageIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string NodeName
    {
        get
        {
            return this.nodeNameField;
        }
        set
        {
            this.nodeNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string RoleName
    {
        get
        {
            return this.roleNameField;
        }
        set
        {
            this.roleNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public int ExecutionPackageId
    {
        get
        {
            return this.executionPackageIdField;
        }
        set
        {
            this.executionPackageIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pnl.gov/RAA/Definition/")]
public partial class DefnActorCriteria : ActorCriteria
{
    
    private int defnActivityIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public int DefnActivityId
    {
        get
        {
            return this.defnActivityIdField;
        }
        set
        {
            this.defnActivityIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pnl.gov/RAA/Definition/")]
public partial class Escalation
{
    
    private string unitField;
    
    private int valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string Unit
    {
        get
        {
            return this.unitField;
        }
        set
        {
            this.unitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public int Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(DefnActivity))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pnl.gov/RAA/Definition/")]
public partial class Activity
{
    
    private Escalation escalationField;
    
    private string activityDescriptorField;
    
    private bool isEditLinkDisplayedField;
    
    private bool isAdhocAllowedBeforeField;
    
    private bool isAdhocAllowedAfterField;
    
    private bool isAdhocAllowedField;
    
    private string buttonTextApproveField;
    
    private string buttonTextAcknowledgeField;
    
    private string buttonTextRejectField;
    
    private bool isDigSigRequiredField;
    
    private bool isActionRequiredField;
    
    private bool isNotificationRequiredField;
    
    private bool isPolymorphicApprovalAllowedField;
    
    private bool isBypassAllowedField;
    
    private int approvalBypassActivityIdField;
    
    private int digsigPayloadIdField;
    
    private bool isAdhocActorAllowedField;
    
    private bool allowBeneficiaryDelegateApproverField;
    
    private bool allowOriginatorDelegateApproverField;
    
    private bool isRejectButtonDisplayedField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public Escalation Escalation
    {
        get
        {
            return this.escalationField;
        }
        set
        {
            this.escalationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string ActivityDescriptor
    {
        get
        {
            return this.activityDescriptorField;
        }
        set
        {
            this.activityDescriptorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public bool IsEditLinkDisplayed
    {
        get
        {
            return this.isEditLinkDisplayedField;
        }
        set
        {
            this.isEditLinkDisplayedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public bool IsAdhocAllowedBefore
    {
        get
        {
            return this.isAdhocAllowedBeforeField;
        }
        set
        {
            this.isAdhocAllowedBeforeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public bool IsAdhocAllowedAfter
    {
        get
        {
            return this.isAdhocAllowedAfterField;
        }
        set
        {
            this.isAdhocAllowedAfterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public bool IsAdhocAllowed
    {
        get
        {
            return this.isAdhocAllowedField;
        }
        set
        {
            this.isAdhocAllowedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=6)]
    public string ButtonTextApprove
    {
        get
        {
            return this.buttonTextApproveField;
        }
        set
        {
            this.buttonTextApproveField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=7)]
    public string ButtonTextAcknowledge
    {
        get
        {
            return this.buttonTextAcknowledgeField;
        }
        set
        {
            this.buttonTextAcknowledgeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=8)]
    public string ButtonTextReject
    {
        get
        {
            return this.buttonTextRejectField;
        }
        set
        {
            this.buttonTextRejectField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=9)]
    public bool IsDigSigRequired
    {
        get
        {
            return this.isDigSigRequiredField;
        }
        set
        {
            this.isDigSigRequiredField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=10)]
    public bool IsActionRequired
    {
        get
        {
            return this.isActionRequiredField;
        }
        set
        {
            this.isActionRequiredField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=11)]
    public bool IsNotificationRequired
    {
        get
        {
            return this.isNotificationRequiredField;
        }
        set
        {
            this.isNotificationRequiredField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=12)]
    public bool IsPolymorphicApprovalAllowed
    {
        get
        {
            return this.isPolymorphicApprovalAllowedField;
        }
        set
        {
            this.isPolymorphicApprovalAllowedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=13)]
    public bool IsBypassAllowed
    {
        get
        {
            return this.isBypassAllowedField;
        }
        set
        {
            this.isBypassAllowedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=14)]
    public int ApprovalBypassActivityId
    {
        get
        {
            return this.approvalBypassActivityIdField;
        }
        set
        {
            this.approvalBypassActivityIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=15)]
    public int DigsigPayloadId
    {
        get
        {
            return this.digsigPayloadIdField;
        }
        set
        {
            this.digsigPayloadIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=16)]
    public bool IsAdhocActorAllowed
    {
        get
        {
            return this.isAdhocActorAllowedField;
        }
        set
        {
            this.isAdhocActorAllowedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=17)]
    public bool AllowBeneficiaryDelegateApprover
    {
        get
        {
            return this.allowBeneficiaryDelegateApproverField;
        }
        set
        {
            this.allowBeneficiaryDelegateApproverField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=18)]
    public bool AllowOriginatorDelegateApprover
    {
        get
        {
            return this.allowOriginatorDelegateApproverField;
        }
        set
        {
            this.allowOriginatorDelegateApproverField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=19)]
    public bool IsRejectButtonDisplayed
    {
        get
        {
            return this.isRejectButtonDisplayedField;
        }
        set
        {
            this.isRejectButtonDisplayedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pnl.gov/RAA/Definition/")]
public partial class Item
{
    
    private string idField;
    
    private string textField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string Id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string Text
    {
        get
        {
            return this.textField;
        }
        set
        {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pnl.gov/RAA/Definition/")]
public partial class ApplStatusWS
{
    
    private string uriField;
    
    private string soapActionField;
    
    private Levels levelField;
    
    private string soapLiteMethodField;
    
    private bool returnDocSwField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string Uri
    {
        get
        {
            return this.uriField;
        }
        set
        {
            this.uriField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string SoapAction
    {
        get
        {
            return this.soapActionField;
        }
        set
        {
            this.soapActionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public Levels Level
    {
        get
        {
            return this.levelField;
        }
        set
        {
            this.levelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string SoapLiteMethod
    {
        get
        {
            return this.soapLiteMethodField;
        }
        set
        {
            this.soapLiteMethodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public bool ReturnDocSw
    {
        get
        {
            return this.returnDocSwField;
        }
        set
        {
            this.returnDocSwField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pnl.gov/RAA/Definition/")]
public enum Levels
{
    
    /// <remarks/>
    NONE,
    
    /// <remarks/>
    PROCESS,
    
    /// <remarks/>
    ACTIVITY,
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(DefnProcess))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pnl.gov/RAA/Definition/")]
public partial class Process
{
    
    private ApplStatusWS applicationWSField;
    
    private Item applicationIRIField;
    
    private string recMgmtClassificationField;
    
    private string recMgmtContainerNumberField;
    
    private string recMgmtInstanceField;
    
    private string recMgmtDataSetIdField;
    
    private string recMgmtRecordTypeField;
    
    private bool recMgmtSendOnApprovalField;
    
    private bool recMgmtSendOnRejectionField;
    
    private bool recMgmtSendOnTerminationField;
    
    private string recMgmtTransformField;
    
    private string docTypeNameField;
    
    private string superUserRoleNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public ApplStatusWS ApplicationWS
    {
        get
        {
            return this.applicationWSField;
        }
        set
        {
            this.applicationWSField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public Item ApplicationIRI
    {
        get
        {
            return this.applicationIRIField;
        }
        set
        {
            this.applicationIRIField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string RecMgmtClassification
    {
        get
        {
            return this.recMgmtClassificationField;
        }
        set
        {
            this.recMgmtClassificationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string RecMgmtContainerNumber
    {
        get
        {
            return this.recMgmtContainerNumberField;
        }
        set
        {
            this.recMgmtContainerNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public string RecMgmtInstance
    {
        get
        {
            return this.recMgmtInstanceField;
        }
        set
        {
            this.recMgmtInstanceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public string RecMgmtDataSetId
    {
        get
        {
            return this.recMgmtDataSetIdField;
        }
        set
        {
            this.recMgmtDataSetIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=6)]
    public string RecMgmtRecordType
    {
        get
        {
            return this.recMgmtRecordTypeField;
        }
        set
        {
            this.recMgmtRecordTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=7)]
    public bool RecMgmtSendOnApproval
    {
        get
        {
            return this.recMgmtSendOnApprovalField;
        }
        set
        {
            this.recMgmtSendOnApprovalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=8)]
    public bool RecMgmtSendOnRejection
    {
        get
        {
            return this.recMgmtSendOnRejectionField;
        }
        set
        {
            this.recMgmtSendOnRejectionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=9)]
    public bool RecMgmtSendOnTermination
    {
        get
        {
            return this.recMgmtSendOnTerminationField;
        }
        set
        {
            this.recMgmtSendOnTerminationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=10)]
    public string RecMgmtTransform
    {
        get
        {
            return this.recMgmtTransformField;
        }
        set
        {
            this.recMgmtTransformField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=11)]
    public string DocTypeName
    {
        get
        {
            return this.docTypeNameField;
        }
        set
        {
            this.docTypeNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=12)]
    public string SuperUserRoleName
    {
        get
        {
            return this.superUserRoleNameField;
        }
        set
        {
            this.superUserRoleNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pnl.gov/RAA/Definition/")]
public enum ActivityDelegateState
{
    
    /// <remarks/>
    PENDING,
    
    /// <remarks/>
    ESCALATED,
    
    /// <remarks/>
    NULL,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pnl.gov/RAA/Definition/")]
public enum TypeOfReplication
{
    
    /// <remarks/>
    NONE,
    
    /// <remarks/>
    ROLENAME,
    
    /// <remarks/>
    USERIDLIST,
    
    /// <remarks/>
    LISTVALUES,
    
    /// <remarks/>
    LISTROLES,
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
public interface DefinitionSoapChannel : DefinitionSoap, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
public partial class DefinitionSoapClient : System.ServiceModel.ClientBase<DefinitionSoap>, DefinitionSoap
{
    
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
    
    public DefinitionSoapClient(EndpointConfiguration endpointConfiguration) : 
            base(DefinitionSoapClient.GetBindingForEndpoint(endpointConfiguration), DefinitionSoapClient.GetEndpointAddress(endpointConfiguration))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public DefinitionSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
            base(DefinitionSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public DefinitionSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(DefinitionSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public DefinitionSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public System.Threading.Tasks.Task<DefnProcess> GetProcessDefnByIdAsync(int Id)
    {
        return base.Channel.GetProcessDefnByIdAsync(Id);
    }
    
    public System.Threading.Tasks.Task<DefnProcess> GetProcessDefnByDocTypeAsync(string DocType, int IRI)
    {
        return base.Channel.GetProcessDefnByDocTypeAsync(DocType, IRI);
    }
    
    public System.Threading.Tasks.Task<System.Xml.Linq.XElement> GetProcessMetaDataXmlNodesAsync(int Id)
    {
        return base.Channel.GetProcessMetaDataXmlNodesAsync(Id);
    }
    
    public virtual System.Threading.Tasks.Task OpenAsync()
    {
        return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
    }
    
    public virtual System.Threading.Tasks.Task CloseAsync()
    {
        return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
    }
    
    private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.DefinitionSoap))
        {
            System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
            result.MaxBufferSize = int.MaxValue;
            result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
            result.MaxReceivedMessageSize = int.MaxValue;
            result.AllowCookies = true;
            result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
            return result;
        }
        if ((endpointConfiguration == EndpointConfiguration.DefinitionSoap12))
        {
            System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
            System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
            textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
            result.Elements.Add(textBindingElement);
            System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
            httpsBindingElement.AllowCookies = true;
            httpsBindingElement.MaxBufferSize = int.MaxValue;
            httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
            result.Elements.Add(httpsBindingElement);
            return result;
        }
        throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
    }
    
    private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.DefinitionSoap))
        {
            return new System.ServiceModel.EndpointAddress("https://approvalstest.pnl.gov/WebServices/Definition.asmx");
        }
        if ((endpointConfiguration == EndpointConfiguration.DefinitionSoap12))
        {
            return new System.ServiceModel.EndpointAddress("https://approvalstest.pnl.gov/WebServices/Definition.asmx");
        }
        throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
    }
    
    public enum EndpointConfiguration
    {
        
        DefinitionSoap,
        
        DefinitionSoap12,
    }
}
