//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace approvals.routing
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://pnl.gov/RAA/Routing/", ConfigurationName="approvals.routing.RoutingSoap")]
    public interface RoutingSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pnl.gov/RAA/Routing/InstantiateProcess", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ActorCriteria))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Activity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Process))]
        System.Threading.Tasks.Task<approvals.routing.InstantiateProcessResponse> InstantiateProcessAsync(approvals.routing.InstantiateProcessRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pnl.gov/RAA/Routing/testEx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ActorCriteria))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Activity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Process))]
        System.Threading.Tasks.Task<string> testExAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pnl.gov/RAA/Routing/InstantiateLOProcess", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ActorCriteria))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Activity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Process))]
        System.Threading.Tasks.Task InstantiateLOProcessAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pnl.gov/RAA/Routing/InstantiatePdfLOProcess", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ActorCriteria))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Activity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Process))]
        System.Threading.Tasks.Task InstantiatePdfLOProcessAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pnl.gov/RAA/Routing/InstantiateImageLOProcess", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ActorCriteria))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Activity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Process))]
        System.Threading.Tasks.Task InstantiateImageLOProcessAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pnl.gov/RAA/Routing/TerminateByProcess", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ActorCriteria))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Activity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Process))]
        System.Threading.Tasks.Task<approvals.routing.TerminationResponse> TerminateByProcessAsync(int InstProcessId, approvals.routing.NetworkIdentification1 TerminatingUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pnl.gov/RAA/Routing/TerminateByProcessNoStatusing", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ActorCriteria))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Activity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Process))]
        System.Threading.Tasks.Task<approvals.routing.TerminationResponse> TerminateByProcessNoStatusingAsync(int InstProcessId, approvals.routing.NetworkIdentification1 TerminatingUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pnl.gov/RAA/Routing/GetTRIMInfoByProcess", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ActorCriteria))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Activity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Process))]
        System.Threading.Tasks.Task<System.Xml.Linq.XElement> GetTRIMInfoByProcessAsync(int InstProcessId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pnl.gov/RAA/Routing/GetStatusByProcess", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ActorCriteria))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Activity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Process))]
        System.Threading.Tasks.Task<approvals.routing.InstProcess> GetStatusByProcessAsync(int InstProcessId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pnl.gov/RAA/Routing/getPendingActivitiesByDoc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ActorCriteria))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Activity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Process))]
        System.Threading.Tasks.Task<approvals.routing.InstActivity[]> getPendingActivitiesByDocAsync(string DocumentTypeName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pnl.gov/RAA/Routing/getTaskListByPerson", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ActorCriteria))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Activity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Process))]
        System.Threading.Tasks.Task<System.Xml.Linq.XElement> getTaskListByPersonAsync(approvals.routing.NetworkIdentification1 TaskListUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pnl.gov/RAA/Routing/getTaskListByPersonAndDocTypeName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ActorCriteria))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Activity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Process))]
        System.Threading.Tasks.Task<System.Xml.Linq.XElement> getTaskListByPersonAndDocTypeNameAsync(approvals.routing.NetworkIdentification1 TaskListUser, string Doc_Type_Name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pnl.gov/RAA/Routing/getTaskListGA", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ActorCriteria))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Activity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Process))]
        System.Threading.Tasks.Task<System.Xml.Linq.XElement> getTaskListGAAsync(approvals.routing.NetworkIdentification1 TaskListUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pnl.gov/RAA/Routing/getTaskListSubordinate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ActorCriteria))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Activity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Process))]
        System.Threading.Tasks.Task<System.Xml.Linq.XElement> getTaskListSubordinateAsync(approvals.routing.NetworkIdentification1 TaskListUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pnl.gov/RAA/Routing/getTaskListByPersonCTL", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ActorCriteria))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Activity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Process))]
        System.Threading.Tasks.Task<System.Xml.Linq.XElement> getTaskListByPersonCTLAsync(approvals.routing.NetworkIdentification1 TaskListUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pnl.gov/RAA/Routing/GetSubmittedProcesses", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ActorCriteria))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Activity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Process))]
        System.Threading.Tasks.Task<System.Xml.Linq.XElement> GetSubmittedProcessesAsync(approvals.routing.NetworkIdentification1 OriginatorUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pnl.gov/RAA/Routing/getPendingProcesses", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ActorCriteria))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Activity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Process))]
        System.Threading.Tasks.Task<System.Xml.Linq.XElement> getPendingProcessesAsync(approvals.routing.NetworkIdentification1 OriginatorUser, approvals.routing.NetworkIdentification1 BeneficiaryUser, string Document_ID, string Doc_Type_Name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pnl.gov/RAA/Routing/getDocument", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ActorCriteria))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Activity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Process))]
        System.Threading.Tasks.Task<System.Xml.Linq.XElement> getDocumentAsync(int processId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pnl.gov/RAA/Routing/getCompletedDocument", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ActorCriteria))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Activity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Process))]
        System.Threading.Tasks.Task<System.Xml.Linq.XElement> getCompletedDocumentAsync(int processId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pnl.gov/RAA/Routing/UpdateDocument", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ActorCriteria))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Activity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Process))]
        System.Threading.Tasks.Task<approvals.routing.UpdateDocumentResponse> UpdateDocumentAsync(approvals.routing.UpdateDocumentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pnl.gov/RAA/Routing/sendAction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ActorCriteria))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Activity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Process))]
        System.Threading.Tasks.Task<approvals.routing.sendActionResponse1> sendActionAsync(approvals.routing.sendActionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pnl.gov/RAA/Routing/addAdhocActor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ActorCriteria))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Activity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Process))]
        System.Threading.Tasks.Task<approvals.routing.addAdhocActorResponse1> addAdhocActorAsync(approvals.routing.addAdhocActorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pnl.gov/RAA/Routing/StatusApplication", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ActorCriteria))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Activity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Process))]
        System.Threading.Tasks.Task StatusApplicationAsync(int ProcessID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pnl.gov/RAA/Routing/TestStatusApplication", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ActorCriteria))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Activity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Process))]
        System.Threading.Tasks.Task TestStatusApplicationAsync(int ProcessID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pnl.gov/RAA/Routing/ProcessLOApprovalsStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ActorCriteria))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Activity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Process))]
        System.Threading.Tasks.Task ProcessLOApprovalsStatusAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pnl.gov/RAA/Routing/ProcessLOApprovalsStatusWithAdhoc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ActorCriteria))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Activity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Process))]
        System.Threading.Tasks.Task ProcessLOApprovalsStatusWithAdhocAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pnl.gov/RAA/Routing/GetLOFormData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ActorCriteria))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Activity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Process))]
        System.Threading.Tasks.Task<System.Xml.Linq.XElement> GetLOFormDataAsync(string formGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pnl.gov/RAA/Routing/ReceiveLOFormData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ActorCriteria))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Activity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Process))]
        System.Threading.Tasks.Task ReceiveLOFormDataAsync(string input1, string input2, string input3, string input4);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pnl.gov/RAA/Routing/TestXmlRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ActorCriteria))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Activity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Process))]
        System.Threading.Tasks.Task TestXmlRequestAsync();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pnl.gov/RAA/RoutingPayloadEntity.xsd")]
    public partial class RoutingPayload
    {
        
        private DocMetaData metaDataField;
        
        private Document documentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public DocMetaData MetaData
        {
            get
            {
                return this.metaDataField;
            }
            set
            {
                this.metaDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Document Document
        {
            get
            {
                return this.documentField;
            }
            set
            {
                this.documentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pnl.gov/RAA/RoutingPayloadEntity.xsd")]
    public partial class DocMetaData
    {
        
        private string tRIMClassificationField;
        
        private string tRIMContainerField;
        
        private int applicationIRIField;
        
        private string documentTypeNameField;
        
        private string documentAtAGlanceField;
        
        private string documentIdField;
        
        private string documentEditLinkField;
        
        private NetworkIdentification documentOriginatorField;
        
        private NetworkIdentification documentBeneficiaryField;
        
        private System.Xml.Linq.XElement documentRoutingDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TRIMClassification
        {
            get
            {
                return this.tRIMClassificationField;
            }
            set
            {
                this.tRIMClassificationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TRIMContainer
        {
            get
            {
                return this.tRIMContainerField;
            }
            set
            {
                this.tRIMContainerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int ApplicationIRI
        {
            get
            {
                return this.applicationIRIField;
            }
            set
            {
                this.applicationIRIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DocumentTypeName
        {
            get
            {
                return this.documentTypeNameField;
            }
            set
            {
                this.documentTypeNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string DocumentAtAGlance
        {
            get
            {
                return this.documentAtAGlanceField;
            }
            set
            {
                this.documentAtAGlanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string DocumentId
        {
            get
            {
                return this.documentIdField;
            }
            set
            {
                this.documentIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string DocumentEditLink
        {
            get
            {
                return this.documentEditLinkField;
            }
            set
            {
                this.documentEditLinkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public NetworkIdentification DocumentOriginator
        {
            get
            {
                return this.documentOriginatorField;
            }
            set
            {
                this.documentOriginatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public NetworkIdentification DocumentBeneficiary
        {
            get
            {
                return this.documentBeneficiaryField;
            }
            set
            {
                this.documentBeneficiaryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Xml.Linq.XElement DocumentRoutingData
        {
            get
            {
                return this.documentRoutingDataField;
            }
            set
            {
                this.documentRoutingDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pnl.gov/RAA/RoutingPayloadEntity.xsd")]
    public partial class NetworkIdentification
    {
        
        private string domainField;
        
        private string networkIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Domain
        {
            get
            {
                return this.domainField;
            }
            set
            {
                this.domainField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string NetworkId
        {
            get
            {
                return this.networkIdField;
            }
            set
            {
                this.networkIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pnl.gov/RAA/Routing/")]
    public partial class AddAdhocActorResponse
    {
        
        private SendActionStatus statusCodeField;
        
        private string statusDescriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SendActionStatus StatusCode
        {
            get
            {
                return this.statusCodeField;
            }
            set
            {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string StatusDescription
        {
            get
            {
                return this.statusDescriptionField;
            }
            set
            {
                this.statusDescriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pnl.gov/RAA/Routing/")]
    public enum SendActionStatus
    {
        
        /// <remarks/>
        Success,
        
        /// <remarks/>
        FailPublicKeyMissing,
        
        /// <remarks/>
        FailActivityNotPending,
        
        /// <remarks/>
        FailInvalidActor,
        
        /// <remarks/>
        FailCommentsRequired,
        
        /// <remarks/>
        FailUnrecognizedAction,
        
        /// <remarks/>
        FailPublicKeyValidation,
        
        /// <remarks/>
        FailGeneralError,
        
        /// <remarks/>
        FailInvalidArguments,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pnl.gov/RAA/Routing/")]
    public partial class WebSignData
    {
        
        private string websignIDField;
        
        private string dataField;
        
        private string networkIDField;
        
        private string transIDField;
        
        private string transDescField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string WebsignID
        {
            get
            {
                return this.websignIDField;
            }
            set
            {
                this.websignIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string NetworkID
        {
            get
            {
                return this.networkIDField;
            }
            set
            {
                this.networkIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string TransID
        {
            get
            {
                return this.transIDField;
            }
            set
            {
                this.transIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string TransDesc
        {
            get
            {
                return this.transDescField;
            }
            set
            {
                this.transDescField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pnl.gov/RAA/Routing/")]
    public partial class SendActionResponse
    {
        
        private SendActionStatus statusCodeField;
        
        private string statusDescriptionField;
        
        private WebSignData websignDataField;
        
        private ActivityState newActivityStateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SendActionStatus StatusCode
        {
            get
            {
                return this.statusCodeField;
            }
            set
            {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string StatusDescription
        {
            get
            {
                return this.statusDescriptionField;
            }
            set
            {
                this.statusDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public WebSignData WebsignData
        {
            get
            {
                return this.websignDataField;
            }
            set
            {
                this.websignDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public ActivityState NewActivityState
        {
            get
            {
                return this.newActivityStateField;
            }
            set
            {
                this.newActivityStateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pnl.gov/RAA/Routing/")]
    public enum ActivityState
    {
        
        /// <remarks/>
        COMPLETE,
        
        /// <remarks/>
        PENDING_ESCALATED,
        
        /// <remarks/>
        PENDING_DIGSIG,
        
        /// <remarks/>
        PENDING,
        
        /// <remarks/>
        NULL,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="Document", Namespace="http://pnl.gov/RAA/Routing/")]
    public partial class Document1
    {
        
        private string fileExtensionField;
        
        private string mimeTypeField;
        
        private byte[] contentField;
        
        private string xslStylesheetField;
        
        private string asciiContentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FileExtension
        {
            get
            {
                return this.fileExtensionField;
            }
            set
            {
                this.fileExtensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MimeType
        {
            get
            {
                return this.mimeTypeField;
            }
            set
            {
                this.mimeTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=2)]
        public byte[] Content
        {
            get
            {
                return this.contentField;
            }
            set
            {
                this.contentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string XslStylesheet
        {
            get
            {
                return this.xslStylesheetField;
            }
            set
            {
                this.xslStylesheetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string AsciiContent
        {
            get
            {
                return this.asciiContentField;
            }
            set
            {
                this.asciiContentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pnl.gov/RAA/Routing/")]
    public partial class Relationship
    {
        
        private int relationshipActivityIdField;
        
        private string relationshipActivityNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int RelationshipActivityId
        {
            get
            {
                return this.relationshipActivityIdField;
            }
            set
            {
                this.relationshipActivityIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string RelationshipActivityName
        {
            get
            {
                return this.relationshipActivityNameField;
            }
            set
            {
                this.relationshipActivityNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Actor))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pnl.gov/RAA/Routing/")]
    public partial class Person
    {
        
        private string emplidField;
        
        private string hanfordIdField;
        
        private NetworkIdentification1 networkIdField;
        
        private string fullNameField;
        
        private NetworkIdentification1 authNetworkIdField;
        
        private string idOfChoiceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Emplid
        {
            get
            {
                return this.emplidField;
            }
            set
            {
                this.emplidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string HanfordId
        {
            get
            {
                return this.hanfordIdField;
            }
            set
            {
                this.hanfordIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public NetworkIdentification1 NetworkId
        {
            get
            {
                return this.networkIdField;
            }
            set
            {
                this.networkIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string FullName
        {
            get
            {
                return this.fullNameField;
            }
            set
            {
                this.fullNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public NetworkIdentification1 AuthNetworkId
        {
            get
            {
                return this.authNetworkIdField;
            }
            set
            {
                this.authNetworkIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string IdOfChoice
        {
            get
            {
                return this.idOfChoiceField;
            }
            set
            {
                this.idOfChoiceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="NetworkIdentification", Namespace="http://pnl.gov/RAA/Routing/")]
    public partial class NetworkIdentification1
    {
        
        private string domainField;
        
        private string networkIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Domain
        {
            get
            {
                return this.domainField;
            }
            set
            {
                this.domainField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string NetworkId
        {
            get
            {
                return this.networkIdField;
            }
            set
            {
                this.networkIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pnl.gov/RAA/Routing/")]
    public partial class Actor : Person
    {
        
        private bool isDelegateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool IsDelegate
        {
            get
            {
                return this.isDelegateField;
            }
            set
            {
                this.isDelegateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InstActorCriteria))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pnl.gov/RAA/Routing/")]
    public partial class ActorCriteria
    {
        
        private string nameField;
        
        private string nodeNameField;
        
        private string roleNameField;
        
        private int executionPackageIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string NodeName
        {
            get
            {
                return this.nodeNameField;
            }
            set
            {
                this.nodeNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string RoleName
        {
            get
            {
                return this.roleNameField;
            }
            set
            {
                this.roleNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int ExecutionPackageId
        {
            get
            {
                return this.executionPackageIdField;
            }
            set
            {
                this.executionPackageIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pnl.gov/RAA/Routing/")]
    public partial class InstActorCriteria : ActorCriteria
    {
        
        private Actor[] instActorsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public Actor[] InstActors
        {
            get
            {
                return this.instActorsField;
            }
            set
            {
                this.instActorsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pnl.gov/RAA/Routing/")]
    public partial class Escalation
    {
        
        private string unitField;
        
        private int valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Unit
        {
            get
            {
                return this.unitField;
            }
            set
            {
                this.unitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InstActivity))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pnl.gov/RAA/Routing/")]
    public partial class Activity
    {
        
        private Escalation escalationField;
        
        private string activityDescriptorField;
        
        private bool isEditLinkDisplayedField;
        
        private bool isAdhocAllowedBeforeField;
        
        private bool isAdhocAllowedAfterField;
        
        private bool isAdhocAllowedField;
        
        private string buttonTextApproveField;
        
        private string buttonTextAcknowledgeField;
        
        private string buttonTextRejectField;
        
        private bool isDigSigRequiredField;
        
        private bool isActionRequiredField;
        
        private bool isNotificationRequiredField;
        
        private bool isPolymorphicApprovalAllowedField;
        
        private bool isBypassAllowedField;
        
        private int approvalBypassActivityIdField;
        
        private int digsigPayloadIdField;
        
        private bool isAdhocActorAllowedField;
        
        private bool allowBeneficiaryDelegateApproverField;
        
        private bool allowOriginatorDelegateApproverField;
        
        private bool isRejectButtonDisplayedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Escalation Escalation
        {
            get
            {
                return this.escalationField;
            }
            set
            {
                this.escalationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ActivityDescriptor
        {
            get
            {
                return this.activityDescriptorField;
            }
            set
            {
                this.activityDescriptorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool IsEditLinkDisplayed
        {
            get
            {
                return this.isEditLinkDisplayedField;
            }
            set
            {
                this.isEditLinkDisplayedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool IsAdhocAllowedBefore
        {
            get
            {
                return this.isAdhocAllowedBeforeField;
            }
            set
            {
                this.isAdhocAllowedBeforeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool IsAdhocAllowedAfter
        {
            get
            {
                return this.isAdhocAllowedAfterField;
            }
            set
            {
                this.isAdhocAllowedAfterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool IsAdhocAllowed
        {
            get
            {
                return this.isAdhocAllowedField;
            }
            set
            {
                this.isAdhocAllowedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ButtonTextApprove
        {
            get
            {
                return this.buttonTextApproveField;
            }
            set
            {
                this.buttonTextApproveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ButtonTextAcknowledge
        {
            get
            {
                return this.buttonTextAcknowledgeField;
            }
            set
            {
                this.buttonTextAcknowledgeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ButtonTextReject
        {
            get
            {
                return this.buttonTextRejectField;
            }
            set
            {
                this.buttonTextRejectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public bool IsDigSigRequired
        {
            get
            {
                return this.isDigSigRequiredField;
            }
            set
            {
                this.isDigSigRequiredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public bool IsActionRequired
        {
            get
            {
                return this.isActionRequiredField;
            }
            set
            {
                this.isActionRequiredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public bool IsNotificationRequired
        {
            get
            {
                return this.isNotificationRequiredField;
            }
            set
            {
                this.isNotificationRequiredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public bool IsPolymorphicApprovalAllowed
        {
            get
            {
                return this.isPolymorphicApprovalAllowedField;
            }
            set
            {
                this.isPolymorphicApprovalAllowedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public bool IsBypassAllowed
        {
            get
            {
                return this.isBypassAllowedField;
            }
            set
            {
                this.isBypassAllowedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public int ApprovalBypassActivityId
        {
            get
            {
                return this.approvalBypassActivityIdField;
            }
            set
            {
                this.approvalBypassActivityIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public int DigsigPayloadId
        {
            get
            {
                return this.digsigPayloadIdField;
            }
            set
            {
                this.digsigPayloadIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public bool IsAdhocActorAllowed
        {
            get
            {
                return this.isAdhocActorAllowedField;
            }
            set
            {
                this.isAdhocActorAllowedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public bool AllowBeneficiaryDelegateApprover
        {
            get
            {
                return this.allowBeneficiaryDelegateApproverField;
            }
            set
            {
                this.allowBeneficiaryDelegateApproverField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public bool AllowOriginatorDelegateApprover
        {
            get
            {
                return this.allowOriginatorDelegateApproverField;
            }
            set
            {
                this.allowOriginatorDelegateApproverField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public bool IsRejectButtonDisplayed
        {
            get
            {
                return this.isRejectButtonDisplayedField;
            }
            set
            {
                this.isRejectButtonDisplayedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pnl.gov/RAA/Routing/")]
    public partial class InstActivity : Activity
    {
        
        private InstActorCriteria[] instActorCriteriasField;
        
        private Relationship[] instParentRelationshipsField;
        
        private Relationship[] instChildRelationshipsField;
        
        private int instActivityIdField;
        
        private int instProcessIdField;
        
        private bool isGhostField;
        
        private bool isAdhocField;
        
        private bool isCurrentPendingField;
        
        private string currentPendingDateTimeField;
        
        private string statusChangeDateTimeField;
        
        private string stateField;
        
        private string statusField;
        
        private string commentField;
        
        private string newReviewerCommentsField;
        
        private Actor statusChangeActorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public InstActorCriteria[] InstActorCriterias
        {
            get
            {
                return this.instActorCriteriasField;
            }
            set
            {
                this.instActorCriteriasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public Relationship[] InstParentRelationships
        {
            get
            {
                return this.instParentRelationshipsField;
            }
            set
            {
                this.instParentRelationshipsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public Relationship[] InstChildRelationships
        {
            get
            {
                return this.instChildRelationshipsField;
            }
            set
            {
                this.instChildRelationshipsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int InstActivityId
        {
            get
            {
                return this.instActivityIdField;
            }
            set
            {
                this.instActivityIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int InstProcessId
        {
            get
            {
                return this.instProcessIdField;
            }
            set
            {
                this.instProcessIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool IsGhost
        {
            get
            {
                return this.isGhostField;
            }
            set
            {
                this.isGhostField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public bool IsAdhoc
        {
            get
            {
                return this.isAdhocField;
            }
            set
            {
                this.isAdhocField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool IsCurrentPending
        {
            get
            {
                return this.isCurrentPendingField;
            }
            set
            {
                this.isCurrentPendingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string CurrentPendingDateTime
        {
            get
            {
                return this.currentPendingDateTimeField;
            }
            set
            {
                this.currentPendingDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string StatusChangeDateTime
        {
            get
            {
                return this.statusChangeDateTimeField;
            }
            set
            {
                this.statusChangeDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string State
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Comment
        {
            get
            {
                return this.commentField;
            }
            set
            {
                this.commentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string NewReviewerComments
        {
            get
            {
                return this.newReviewerCommentsField;
            }
            set
            {
                this.newReviewerCommentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public Actor StatusChangeActor
        {
            get
            {
                return this.statusChangeActorField;
            }
            set
            {
                this.statusChangeActorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pnl.gov/RAA/Routing/")]
    public partial class Item
    {
        
        private string idField;
        
        private string textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pnl.gov/RAA/Routing/")]
    public partial class ApplStatusWS
    {
        
        private string uriField;
        
        private string soapActionField;
        
        private Levels levelField;
        
        private string soapLiteMethodField;
        
        private bool returnDocSwField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Uri
        {
            get
            {
                return this.uriField;
            }
            set
            {
                this.uriField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SoapAction
        {
            get
            {
                return this.soapActionField;
            }
            set
            {
                this.soapActionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Levels Level
        {
            get
            {
                return this.levelField;
            }
            set
            {
                this.levelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SoapLiteMethod
        {
            get
            {
                return this.soapLiteMethodField;
            }
            set
            {
                this.soapLiteMethodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool ReturnDocSw
        {
            get
            {
                return this.returnDocSwField;
            }
            set
            {
                this.returnDocSwField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pnl.gov/RAA/Routing/")]
    public enum Levels
    {
        
        /// <remarks/>
        NONE,
        
        /// <remarks/>
        PROCESS,
        
        /// <remarks/>
        ACTIVITY,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InstProcess))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pnl.gov/RAA/Routing/")]
    public partial class Process
    {
        
        private ApplStatusWS applicationWSField;
        
        private Item applicationIRIField;
        
        private string recMgmtClassificationField;
        
        private string recMgmtContainerNumberField;
        
        private string recMgmtInstanceField;
        
        private string recMgmtDataSetIdField;
        
        private string recMgmtRecordTypeField;
        
        private bool recMgmtSendOnApprovalField;
        
        private bool recMgmtSendOnRejectionField;
        
        private bool recMgmtSendOnTerminationField;
        
        private string recMgmtTransformField;
        
        private string docTypeNameField;
        
        private string superUserRoleNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ApplStatusWS ApplicationWS
        {
            get
            {
                return this.applicationWSField;
            }
            set
            {
                this.applicationWSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Item ApplicationIRI
        {
            get
            {
                return this.applicationIRIField;
            }
            set
            {
                this.applicationIRIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string RecMgmtClassification
        {
            get
            {
                return this.recMgmtClassificationField;
            }
            set
            {
                this.recMgmtClassificationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string RecMgmtContainerNumber
        {
            get
            {
                return this.recMgmtContainerNumberField;
            }
            set
            {
                this.recMgmtContainerNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string RecMgmtInstance
        {
            get
            {
                return this.recMgmtInstanceField;
            }
            set
            {
                this.recMgmtInstanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string RecMgmtDataSetId
        {
            get
            {
                return this.recMgmtDataSetIdField;
            }
            set
            {
                this.recMgmtDataSetIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string RecMgmtRecordType
        {
            get
            {
                return this.recMgmtRecordTypeField;
            }
            set
            {
                this.recMgmtRecordTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool RecMgmtSendOnApproval
        {
            get
            {
                return this.recMgmtSendOnApprovalField;
            }
            set
            {
                this.recMgmtSendOnApprovalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public bool RecMgmtSendOnRejection
        {
            get
            {
                return this.recMgmtSendOnRejectionField;
            }
            set
            {
                this.recMgmtSendOnRejectionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public bool RecMgmtSendOnTermination
        {
            get
            {
                return this.recMgmtSendOnTerminationField;
            }
            set
            {
                this.recMgmtSendOnTerminationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string RecMgmtTransform
        {
            get
            {
                return this.recMgmtTransformField;
            }
            set
            {
                this.recMgmtTransformField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string DocTypeName
        {
            get
            {
                return this.docTypeNameField;
            }
            set
            {
                this.docTypeNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string SuperUserRoleName
        {
            get
            {
                return this.superUserRoleNameField;
            }
            set
            {
                this.superUserRoleNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pnl.gov/RAA/Routing/")]
    public partial class InstProcess : Process
    {
        
        private InstActivity[] instActivitiesField;
        
        private string documentAtAGlanceDescriptionField;
        
        private int instProcessIdField;
        
        private string instantiationDateTimeField;
        
        private string stateField;
        
        private string statusField;
        
        private string documentIdField;
        
        private string documentEditLinkField;
        
        private Person documentOriginatorField;
        
        private Person documentBeneficiaryField;
        
        private Document1 processDocumentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public InstActivity[] InstActivities
        {
            get
            {
                return this.instActivitiesField;
            }
            set
            {
                this.instActivitiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DocumentAtAGlanceDescription
        {
            get
            {
                return this.documentAtAGlanceDescriptionField;
            }
            set
            {
                this.documentAtAGlanceDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int InstProcessId
        {
            get
            {
                return this.instProcessIdField;
            }
            set
            {
                this.instProcessIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string InstantiationDateTime
        {
            get
            {
                return this.instantiationDateTimeField;
            }
            set
            {
                this.instantiationDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string State
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string DocumentId
        {
            get
            {
                return this.documentIdField;
            }
            set
            {
                this.documentIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string DocumentEditLink
        {
            get
            {
                return this.documentEditLinkField;
            }
            set
            {
                this.documentEditLinkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public Person DocumentOriginator
        {
            get
            {
                return this.documentOriginatorField;
            }
            set
            {
                this.documentOriginatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public Person DocumentBeneficiary
        {
            get
            {
                return this.documentBeneficiaryField;
            }
            set
            {
                this.documentBeneficiaryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public Document1 ProcessDocument
        {
            get
            {
                return this.processDocumentField;
            }
            set
            {
                this.processDocumentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pnl.gov/RAA/Routing/")]
    public partial class TerminationResponse
    {
        
        private int resultIdField;
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ResultId
        {
            get
            {
                return this.resultIdField;
            }
            set
            {
                this.resultIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pnl.gov/RAA/Routing/")]
    public partial class RoutingResponse
    {
        
        private int instProcessIdField;
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int InstProcessId
        {
            get
            {
                return this.instProcessIdField;
            }
            set
            {
                this.instProcessIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pnl.gov/RAA/RoutingPayloadEntity.xsd")]
    public partial class Document
    {
        
        private string fileExtensionField;
        
        private string mimeTypeField;
        
        private byte[] contentField;
        
        private string xslStylesheetField;
        
        private string asciiContentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FileExtension
        {
            get
            {
                return this.fileExtensionField;
            }
            set
            {
                this.fileExtensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MimeType
        {
            get
            {
                return this.mimeTypeField;
            }
            set
            {
                this.mimeTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=2)]
        public byte[] Content
        {
            get
            {
                return this.contentField;
            }
            set
            {
                this.contentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string XslStylesheet
        {
            get
            {
                return this.xslStylesheetField;
            }
            set
            {
                this.xslStylesheetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string AsciiContent
        {
            get
            {
                return this.asciiContentField;
            }
            set
            {
                this.asciiContentField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InstantiateProcess", WrapperNamespace="http://pnl.gov/RAA/Routing/", IsWrapped=true)]
    public partial class InstantiateProcessRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pnl.gov/RAA/RoutingPayloadEntity.xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://pnl.gov/RAA/RoutingPayloadEntity.xsd")]
        public approvals.routing.RoutingPayload RoutingPayload;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pnl.gov/RAA/Routing/", Order=1)]
        public approvals.routing.NetworkIdentification1 InstantiateUser;
        
        public InstantiateProcessRequest()
        {
        }
        
        public InstantiateProcessRequest(approvals.routing.RoutingPayload RoutingPayload, approvals.routing.NetworkIdentification1 InstantiateUser)
        {
            this.RoutingPayload = RoutingPayload;
            this.InstantiateUser = InstantiateUser;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InstantiateProcessResponse", WrapperNamespace="http://pnl.gov/RAA/Routing/", IsWrapped=true)]
    public partial class InstantiateProcessResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pnl.gov/RAA/Routing/", Order=0)]
        public approvals.routing.RoutingResponse InstantiateProcessResult;
        
        public InstantiateProcessResponse()
        {
        }
        
        public InstantiateProcessResponse(approvals.routing.RoutingResponse InstantiateProcessResult)
        {
            this.InstantiateProcessResult = InstantiateProcessResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateDocument", WrapperNamespace="http://pnl.gov/RAA/Routing/", IsWrapped=true)]
    public partial class UpdateDocumentRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pnl.gov/RAA/Routing/", Order=0)]
        public int processId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pnl.gov/RAA/Routing/", Order=1)]
        public string actionPayload;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pnl.gov/RAA/Routing/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] signedString;
        
        public UpdateDocumentRequest()
        {
        }
        
        public UpdateDocumentRequest(int processId, string actionPayload, byte[] signedString)
        {
            this.processId = processId;
            this.actionPayload = actionPayload;
            this.signedString = signedString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateDocumentResponse", WrapperNamespace="http://pnl.gov/RAA/Routing/", IsWrapped=true)]
    public partial class UpdateDocumentResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pnl.gov/RAA/Routing/", Order=0)]
        public approvals.routing.SendActionResponse UpdateDocumentResult;
        
        public UpdateDocumentResponse()
        {
        }
        
        public UpdateDocumentResponse(approvals.routing.SendActionResponse UpdateDocumentResult)
        {
            this.UpdateDocumentResult = UpdateDocumentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendAction", WrapperNamespace="http://pnl.gov/RAA/Routing/", IsWrapped=true)]
    public partial class sendActionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pnl.gov/RAA/Routing/", Order=0)]
        public int processId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pnl.gov/RAA/Routing/", Order=1)]
        public string actionPayload;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pnl.gov/RAA/Routing/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] SignedString;
        
        public sendActionRequest()
        {
        }
        
        public sendActionRequest(int processId, string actionPayload, byte[] SignedString)
        {
            this.processId = processId;
            this.actionPayload = actionPayload;
            this.SignedString = SignedString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendActionResponse", WrapperNamespace="http://pnl.gov/RAA/Routing/", IsWrapped=true)]
    public partial class sendActionResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pnl.gov/RAA/Routing/", Order=0)]
        public approvals.routing.SendActionResponse sendActionResult;
        
        public sendActionResponse1()
        {
        }
        
        public sendActionResponse1(approvals.routing.SendActionResponse sendActionResult)
        {
            this.sendActionResult = sendActionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addAdhocActor", WrapperNamespace="http://pnl.gov/RAA/Routing/", IsWrapped=true)]
    public partial class addAdhocActorRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pnl.gov/RAA/Routing/", Order=0)]
        public int activityId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pnl.gov/RAA/Routing/", Order=1)]
        public string actionPayload;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pnl.gov/RAA/Routing/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] SignedString;
        
        public addAdhocActorRequest()
        {
        }
        
        public addAdhocActorRequest(int activityId, string actionPayload, byte[] SignedString)
        {
            this.activityId = activityId;
            this.actionPayload = actionPayload;
            this.SignedString = SignedString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addAdhocActorResponse", WrapperNamespace="http://pnl.gov/RAA/Routing/", IsWrapped=true)]
    public partial class addAdhocActorResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pnl.gov/RAA/Routing/", Order=0)]
        public approvals.routing.AddAdhocActorResponse addAdhocActorResult;
        
        public addAdhocActorResponse1()
        {
        }
        
        public addAdhocActorResponse1(approvals.routing.AddAdhocActorResponse addAdhocActorResult)
        {
            this.addAdhocActorResult = addAdhocActorResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public interface RoutingSoapChannel : approvals.routing.RoutingSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public partial class RoutingSoapClient : System.ServiceModel.ClientBase<approvals.routing.RoutingSoap>, approvals.routing.RoutingSoap
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public RoutingSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(RoutingSoapClient.GetBindingForEndpoint(endpointConfiguration), RoutingSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RoutingSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(RoutingSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RoutingSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(RoutingSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RoutingSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<approvals.routing.InstantiateProcessResponse> approvals.routing.RoutingSoap.InstantiateProcessAsync(approvals.routing.InstantiateProcessRequest request)
        {
            return base.Channel.InstantiateProcessAsync(request);
        }
        
        public System.Threading.Tasks.Task<approvals.routing.InstantiateProcessResponse> InstantiateProcessAsync(approvals.routing.RoutingPayload RoutingPayload, approvals.routing.NetworkIdentification1 InstantiateUser)
        {
            approvals.routing.InstantiateProcessRequest inValue = new approvals.routing.InstantiateProcessRequest();
            inValue.RoutingPayload = RoutingPayload;
            inValue.InstantiateUser = InstantiateUser;
            return ((approvals.routing.RoutingSoap)(this)).InstantiateProcessAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<string> testExAsync()
        {
            return base.Channel.testExAsync();
        }
        
        public System.Threading.Tasks.Task InstantiateLOProcessAsync()
        {
            return base.Channel.InstantiateLOProcessAsync();
        }
        
        public System.Threading.Tasks.Task InstantiatePdfLOProcessAsync()
        {
            return base.Channel.InstantiatePdfLOProcessAsync();
        }
        
        public System.Threading.Tasks.Task InstantiateImageLOProcessAsync()
        {
            return base.Channel.InstantiateImageLOProcessAsync();
        }
        
        public System.Threading.Tasks.Task<approvals.routing.TerminationResponse> TerminateByProcessAsync(int InstProcessId, approvals.routing.NetworkIdentification1 TerminatingUser)
        {
            return base.Channel.TerminateByProcessAsync(InstProcessId, TerminatingUser);
        }
        
        public System.Threading.Tasks.Task<approvals.routing.TerminationResponse> TerminateByProcessNoStatusingAsync(int InstProcessId, approvals.routing.NetworkIdentification1 TerminatingUser)
        {
            return base.Channel.TerminateByProcessNoStatusingAsync(InstProcessId, TerminatingUser);
        }
        
        public System.Threading.Tasks.Task<System.Xml.Linq.XElement> GetTRIMInfoByProcessAsync(int InstProcessId)
        {
            return base.Channel.GetTRIMInfoByProcessAsync(InstProcessId);
        }
        
        public System.Threading.Tasks.Task<approvals.routing.InstProcess> GetStatusByProcessAsync(int InstProcessId)
        {
            return base.Channel.GetStatusByProcessAsync(InstProcessId);
        }
        
        public System.Threading.Tasks.Task<approvals.routing.InstActivity[]> getPendingActivitiesByDocAsync(string DocumentTypeName)
        {
            return base.Channel.getPendingActivitiesByDocAsync(DocumentTypeName);
        }
        
        public System.Threading.Tasks.Task<System.Xml.Linq.XElement> getTaskListByPersonAsync(approvals.routing.NetworkIdentification1 TaskListUser)
        {
            return base.Channel.getTaskListByPersonAsync(TaskListUser);
        }
        
        public System.Threading.Tasks.Task<System.Xml.Linq.XElement> getTaskListByPersonAndDocTypeNameAsync(approvals.routing.NetworkIdentification1 TaskListUser, string Doc_Type_Name)
        {
            return base.Channel.getTaskListByPersonAndDocTypeNameAsync(TaskListUser, Doc_Type_Name);
        }
        
        public System.Threading.Tasks.Task<System.Xml.Linq.XElement> getTaskListGAAsync(approvals.routing.NetworkIdentification1 TaskListUser)
        {
            return base.Channel.getTaskListGAAsync(TaskListUser);
        }
        
        public System.Threading.Tasks.Task<System.Xml.Linq.XElement> getTaskListSubordinateAsync(approvals.routing.NetworkIdentification1 TaskListUser)
        {
            return base.Channel.getTaskListSubordinateAsync(TaskListUser);
        }
        
        public System.Threading.Tasks.Task<System.Xml.Linq.XElement> getTaskListByPersonCTLAsync(approvals.routing.NetworkIdentification1 TaskListUser)
        {
            return base.Channel.getTaskListByPersonCTLAsync(TaskListUser);
        }
        
        public System.Threading.Tasks.Task<System.Xml.Linq.XElement> GetSubmittedProcessesAsync(approvals.routing.NetworkIdentification1 OriginatorUser)
        {
            return base.Channel.GetSubmittedProcessesAsync(OriginatorUser);
        }
        
        public System.Threading.Tasks.Task<System.Xml.Linq.XElement> getPendingProcessesAsync(approvals.routing.NetworkIdentification1 OriginatorUser, approvals.routing.NetworkIdentification1 BeneficiaryUser, string Document_ID, string Doc_Type_Name)
        {
            return base.Channel.getPendingProcessesAsync(OriginatorUser, BeneficiaryUser, Document_ID, Doc_Type_Name);
        }
        
        public System.Threading.Tasks.Task<System.Xml.Linq.XElement> getDocumentAsync(int processId)
        {
            return base.Channel.getDocumentAsync(processId);
        }
        
        public System.Threading.Tasks.Task<System.Xml.Linq.XElement> getCompletedDocumentAsync(int processId)
        {
            return base.Channel.getCompletedDocumentAsync(processId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<approvals.routing.UpdateDocumentResponse> approvals.routing.RoutingSoap.UpdateDocumentAsync(approvals.routing.UpdateDocumentRequest request)
        {
            return base.Channel.UpdateDocumentAsync(request);
        }
        
        public System.Threading.Tasks.Task<approvals.routing.UpdateDocumentResponse> UpdateDocumentAsync(int processId, string actionPayload, byte[] signedString)
        {
            approvals.routing.UpdateDocumentRequest inValue = new approvals.routing.UpdateDocumentRequest();
            inValue.processId = processId;
            inValue.actionPayload = actionPayload;
            inValue.signedString = signedString;
            return ((approvals.routing.RoutingSoap)(this)).UpdateDocumentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<approvals.routing.sendActionResponse1> approvals.routing.RoutingSoap.sendActionAsync(approvals.routing.sendActionRequest request)
        {
            return base.Channel.sendActionAsync(request);
        }
        
        public System.Threading.Tasks.Task<approvals.routing.sendActionResponse1> sendActionAsync(int processId, string actionPayload, byte[] SignedString)
        {
            approvals.routing.sendActionRequest inValue = new approvals.routing.sendActionRequest();
            inValue.processId = processId;
            inValue.actionPayload = actionPayload;
            inValue.SignedString = SignedString;
            return ((approvals.routing.RoutingSoap)(this)).sendActionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<approvals.routing.addAdhocActorResponse1> approvals.routing.RoutingSoap.addAdhocActorAsync(approvals.routing.addAdhocActorRequest request)
        {
            return base.Channel.addAdhocActorAsync(request);
        }
        
        public System.Threading.Tasks.Task<approvals.routing.addAdhocActorResponse1> addAdhocActorAsync(int activityId, string actionPayload, byte[] SignedString)
        {
            approvals.routing.addAdhocActorRequest inValue = new approvals.routing.addAdhocActorRequest();
            inValue.activityId = activityId;
            inValue.actionPayload = actionPayload;
            inValue.SignedString = SignedString;
            return ((approvals.routing.RoutingSoap)(this)).addAdhocActorAsync(inValue);
        }
        
        public System.Threading.Tasks.Task StatusApplicationAsync(int ProcessID)
        {
            return base.Channel.StatusApplicationAsync(ProcessID);
        }
        
        public System.Threading.Tasks.Task TestStatusApplicationAsync(int ProcessID)
        {
            return base.Channel.TestStatusApplicationAsync(ProcessID);
        }
        
        public System.Threading.Tasks.Task ProcessLOApprovalsStatusAsync()
        {
            return base.Channel.ProcessLOApprovalsStatusAsync();
        }
        
        public System.Threading.Tasks.Task ProcessLOApprovalsStatusWithAdhocAsync()
        {
            return base.Channel.ProcessLOApprovalsStatusWithAdhocAsync();
        }
        
        public System.Threading.Tasks.Task<System.Xml.Linq.XElement> GetLOFormDataAsync(string formGuid)
        {
            return base.Channel.GetLOFormDataAsync(formGuid);
        }
        
        public System.Threading.Tasks.Task ReceiveLOFormDataAsync(string input1, string input2, string input3, string input4)
        {
            return base.Channel.ReceiveLOFormDataAsync(input1, input2, input3, input4);
        }
        
        public System.Threading.Tasks.Task TestXmlRequestAsync()
        {
            return base.Channel.TestXmlRequestAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.RoutingSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.RoutingSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.RoutingSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://approvalstest.pnl.gov/webservices/routing.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.RoutingSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://approvalstest.pnl.gov/webservices/routing.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            RoutingSoap,
            
            RoutingSoap12,
        }
    }
}
